v1.8.0
remove
1. convert options in subscription config
2. fallback filter options in mixin config
3. sniffer options in mixin config

add
1. tcp keepalive idle option in mixin config
2. fake-ip filter mode option in mixin config
3. respect rule option in mixin config

diff --git a/mihomo/files/mihomo.init b/mihomo/files/mihomo.init
--- a/mihomo/files/mihomo.init
+++ b/mihomo/files/mihomo.init
@@ -25,7 +25,7 @@ start_service() {
 	# get config
 	## app config
 	local scheduled_restart cron_expression profile mixin test_profile fast_reload
-	config_get scheduled_restart "config" "scheduled_restart"
+	config_get_bool scheduled_restart "config" "scheduled_restart" 0
 	config_get cron_expression "config" "cron_expression"
 	config_get profile "config" "profile"
 	config_get_bool mixin "config" "mixin" 0
@@ -34,7 +34,7 @@ start_service() {
 	## proxy config
 	local transparent_proxy transparent_proxy_mode ipv4_dns_hijack ipv6_dns_hijack ipv4_proxy ipv6_proxy router_proxy lan_proxy access_control_mode bypass_china_mainland_ip acl_tcp_dport acl_udp_dport
 	config_get_bool transparent_proxy "proxy" "transparent_proxy" 0
-	config_get transparent_proxy_mode "proxy" "transparent_proxy_mode"
+	config_get transparent_proxy_mode "proxy" "transparent_proxy_mode" "tproxy"
 	config_get_bool ipv4_dns_hijack "proxy" "ipv4_dns_hijack" 0
 	config_get_bool ipv6_dns_hijack "proxy" "ipv6_dns_hijack" 0
 	config_get_bool ipv4_proxy "proxy" "ipv4_proxy" 0
@@ -43,19 +43,18 @@ start_service() {
 	config_get_bool lan_proxy "proxy" "lan_proxy" 0
 	config_get access_control_mode "proxy" "access_control_mode"
 	config_get_bool bypass_china_mainland_ip "proxy" "bypass_china_mainland_ip" 0
-	config_get acl_tcp_dport "proxy" "acl_tcp_dport" "1-65535"
-	config_get acl_udp_dport "proxy" "acl_udp_dport" "1-65535"
+	config_get acl_tcp_dport "proxy" "acl_tcp_dport" "0-65535"
+	config_get acl_udp_dport "proxy" "acl_udp_dport" "0-65535"
 	## mixin config
 	### general
-	local mode match_process outbound_interface ipv6 unify_delay tcp_concurrent tcp_keep_alive_interval log_level
-	config_get mode "mixin" "mode"
-	config_get match_process "mixin" "match_process"
+	local mode match_process outbound_interface ipv6 tcp_keep_alive_idle tcp_keep_alive_interval log_level
+	config_get mode "mixin" "mode" "rule"
+	config_get match_process "mixin" "match_process" "off"
 	config_get outbound_interface "mixin" "outbound_interface"
 	config_get_bool ipv6 "mixin" "ipv6" 0
-	config_get_bool unify_delay "mixin" "unify_delay" 0
-	config_get_bool tcp_concurrent "mixin" "tcp_concurrent" 0
-	config_get tcp_keep_alive_interval "mixin" "tcp_keep_alive_interval" 600
-	config_get log_level "mixin" "log_level"
+	config_get tcp_keep_alive_idle "mixin" "tcp_keep_alive_idle" 600
+	config_get tcp_keep_alive_interval "mixin" "tcp_keep_alive_interval" 15
+	config_get log_level "mixin" "log_level" "info"
 	### external control
 	local ui_name ui_url api_port api_secret selection_cache
 	config_get ui_name "mixin" "ui_name"
@@ -74,35 +73,30 @@ start_service() {
 	config_get_bool authentication "mixin" "authentication" 0
 	### tun
 	local tun_stack tun_mtu tun_gso tun_gso_max_size tun_endpoint_independent_nat
-	config_get tun_stack "mixin" "tun_stack"
+	config_get tun_stack "mixin" "tun_stack" "system"
 	config_get tun_mtu "mixin" "tun_mtu" "9000"
 	config_get_bool tun_gso "mixin" "tun_gso" 0
 	config_get tun_gso_max_size "mixin" "tun_gso_max_size" "65536"
 	config_get_bool tun_endpoint_independent_nat "mixin" "tun_endpoint_independent_nat" 0
 	### dns
-	local dns_port dns_mode fake_ip_range fake_ip_filter fake_ip_cache dns_ipv6 dns_system_hosts dns_hosts hosts dns_nameserver dns_fallback_filter dns_nameserver_policy
+	local dns_port dns_mode fake_ip_range fake_ip_filter fake_ip_filter_mode fake_ip_cache dns_respect_rules dns_ipv6 dns_system_hosts dns_hosts hosts dns_nameserver dns_nameserver_policy
 	config_get dns_port "mixin" "dns_port" "1053"
-	config_get dns_mode "mixin" "dns_mode"
+	config_get dns_mode "mixin" "dns_mode" "redir-host"
 	config_get fake_ip_range "mixin" "fake_ip_range" "198.18.0.1/16"
 	config_get_bool fake_ip_filter "mixin" "fake_ip_filter" 0
+	config_get fake_ip_filter_mode "mixin" "fake_ip_filter_mode" "blacklist"
 	config_get_bool fake_ip_cache "mixin" "fake_ip_cache" 0
+	config_get_bool dns_respect_rules "mixin" "dns_respect_rules" 0
 	config_get_bool dns_ipv6 "mixin" "dns_ipv6" 0
 	config_get_bool dns_system_hosts "mixin" "dns_system_hosts" 0
 	config_get_bool dns_hosts "mixin" "dns_hosts" 0
 	config_get_bool hosts "mixin" "hosts" 0
 	config_get_bool dns_nameserver "mixin" "dns_nameserver" 0
-	config_get_bool dns_fallback_filter "mixin" "dns_fallback_filter" 0
 	config_get_bool dns_nameserver_policy "mixin" "dns_nameserver_policy" 0
-	### sniffer
-	local sniffer sniff_dns_mapping sniff_pure_ip sniffer_overwrite_dest
-	config_get_bool sniffer "mixin" "sniffer" 0
-	config_get_bool sniff_dns_mapping "mixin" "sniff_dns_mapping" 0
-	config_get_bool sniff_pure_ip "mixin" "sniff_pure_ip" 0
-	config_get_bool sniffer_overwrite_dest "mixin" "sniffer_overwrite_dest" 0
 	### geox
 	local geoip_format geodata_loader geosite_url geoip_mmdb_url geoip_dat_url geoip_asn_url geox_auto_update geox_update_interval
-	config_get geoip_format "mixin" "geoip_format"
-	config_get geodata_loader "mixin" "geodata_loader"
+	config_get geoip_format "mixin" "geoip_format" "mmdb"
+	config_get geodata_loader "mixin" "geodata_loader" "memconservative"
 	config_get geosite_url "mixin" "geosite_url"
 	config_get geoip_mmdb_url "mixin" "geoip_mmdb_url"
 	config_get geoip_dat_url "mixin" "geoip_dat_url"
@@ -116,53 +110,19 @@ start_service() {
 		log "Use Profile: $profile_name"
 	elif [[ "$profile" == "subscription:"* ]]; then
 		local subscription_section; subscription_section="${profile/subscription:/}"
-		# subscription
 		local subscription_name subscription_url subscription_user_agent
 		config_get subscription_name "$subscription_section" "name"
 		config_get subscription_url "$subscription_section" "url"
 		config_get subscription_user_agent "$subscription_section" "user_agent"
-		# convert
-		local subscription_convert subscription_convert_backend subscription_convert_template
-		config_get_bool subscription_convert "$subscription_section" "convert" 0
-		config_get subscription_convert_backend "$subscription_section" "convert_backend"
-		config_get subscription_convert_template "$subscription_section" "convert_template"
-		# convert advanced
-		local subscription_convert_advanced subscription_convert_include subscription_convert_exclude subscription_convert_udp subscription_convert_emoji subscription_convert_insert_node_type subscription_convert_expand
-		config_get_bool subscription_convert_advanced "$subscription_section" "convert_advanced" 0
-		config_get subscription_convert_include "$subscription_section" "convert_include"
-		config_get subscription_convert_exclude "$subscription_section" "convert_exclude"
-		config_get_bool subscription_convert_udp "$subscription_section" "convert_udp" 0
-		config_get_bool subscription_convert_emoji "$subscription_section" "convert_emoji" 0
-		config_get_bool subscription_convert_insert_node_type "$subscription_section" "convert_insert_node_type" 0
-		config_get_bool subscription_convert_expand "$subscription_section" "convert_expand" 0
-		# generate url
-		local url
-		if [ "$subscription_convert" == 0 ]; then
-			url="$subscription_url"
-		else
-			url="$subscription_convert_backend?target=clash&url=$(echo -n "$subscription_url" | yq -M -o uri)"
-			if [ -n "$subscription_convert_template" ]; then
-				url="$url&config=$(echo -n "$subscription_convert_template" | yq -M -o uri)"
-			fi
-			if [ "$subscription_convert_advanced" == 1 ]; then
-				if [ -n "$subscription_convert_include" ]; then
-					url="$url&include=$(echo -n "$subscription_convert_include" | yq -M -o uri)"
-				fi
-				if [ -n "$subscription_convert_exclude" ]; then
-					url="$url&exclude=$(echo -n "$subscription_convert_exclude" | yq -M -o uri)"
-				fi
-				url="$url&udp=$([ "$subscription_convert_udp" == 1 ] && echo -n "true" || echo -n "false")"
-				url="$url&emoji=$([ "$subscription_convert_emoji" == 1 ] && echo -n "true" || echo -n "false")"
-				url="$url&append_type=$([ "$subscription_convert_insert_node_type" == 1 ] && echo -n "true" || echo -n "false")"
-				url="$url&expand=$([ "$subscription_convert_expand" == 1 ] && echo -n "true" || echo -n "false")"
-			fi
+		curl -s --connect-timeout 15 --retry 3 -o "$RUN_PROFILE_PATH" -L -H "User-Agent: $subscription_user_agent" "$subscription_url"
+		if [ "$?" != 0 ]; then
+			log "Subscription download failed."
+			log "Exiting..."
+			return
 		fi
-		curl -s -o "$RUN_PROFILE_PATH" -L -H "User-Agent: $subscription_user_agent" "$url"
 		log "Use Subscription: $subscription_name"
-	elif [[ "$profile" == "http:"* || "$profile" == "https:"* ]]; then
-		local url; url=$profile
-		curl -s -o "$RUN_PROFILE_PATH" -L -H "User-Agent: mihomo clash.meta clash" "$url"
-		log "Use Url: $url"
+	else
+		return
 	fi
 	# mixin
 	if [ "$mixin" == 0 ]; then
@@ -183,23 +143,21 @@ start_service() {
 	else
 		log "Mixin is enabled, mixin all config."
 		# do mixin
-		log_level="$log_level" mode="$mode" match_process="$match_process" unify_delay="$unify_delay" tcp_concurrent="$tcp_concurrent" tcp_keep_alive_interval="$tcp_keep_alive_interval" ipv6="$ipv6" \
+		log_level="$log_level" mode="$mode" match_process="$match_process" tcp_keep_alive_idle="$tcp_keep_alive_idle" tcp_keep_alive_interval="$tcp_keep_alive_interval" ipv6="$ipv6" \
 		ui_path="ui" ui_name="$ui_name" ui_url="$ui_url" api_listen="0.0.0.0:$api_port" api_secret="$api_secret" selection_cache="$selection_cache" \
 		allow_lan="$allow_lan" http_port="$http_port" socks_port="$socks_port" mixed_port="$mixed_port" redir_port="$redir_port" tproxy_port="$tproxy_port" \
 		tun_stack="$tun_stack" tun_device="$TUN_DEVICE" tun_mtu="$tun_mtu" tun_gso="$tun_gso" tun_gso_max_size="$tun_gso_max_size" tun_endpoint_independent_nat="$tun_endpoint_independent_nat" \
 		dns_enable="true" dns_listen="0.0.0.0:$dns_port" dns_mode="$dns_mode" fake_ip_range="$fake_ip_range" fake_ip_cache="$fake_ip_cache" \
-		dns_ipv6="$dns_ipv6" dns_system_hosts="$dns_system_hosts" dns_hosts="$dns_hosts" \
-		sniffer="$sniffer" sniff_dns_mapping="$sniff_dns_mapping" sniff_pure_ip="$sniff_pure_ip" sniffer_overwrite_dest="$sniffer_overwrite_dest" \
+		dns_respect_rules="$dns_respect_rules" dns_ipv6="$dns_ipv6" dns_system_hosts="$dns_system_hosts" dns_hosts="$dns_hosts" \
 		geoip_format="$geoip_format" geodata_loader="$geodata_loader" geosite_url="$geosite_url" geoip_mmdb_url="$geoip_mmdb_url" geoip_dat_url="$geoip_dat_url" geoip_asn_url="$geoip_asn_url" \
 		geox_auto_update="$geox_auto_update" geox_update_interval="$geox_update_interval" \
 		yq -M -i '
-		.log-level = env(log_level) | .mode = env(mode) | .find-process-mode = env(match_process) | .unified-delay = env(unify_delay) == 1 | .tcp-concurrent = env(tcp_concurrent) == 1 | .keep-alive-interval = env(tcp_keep_alive_interval) | .ipv6 = env(ipv6) == 1 |
+		.log-level = env(log_level) | .mode = env(mode) | .find-process-mode = env(match_process) | .keep-alive-idle = env(tcp_keep_alive_idle) | .keep-alive-interval = env(tcp_keep_alive_interval) | .ipv6 = env(ipv6) == 1 |
 		.external-ui = env(ui_path) | .external-ui-name = env(ui_name) | .external-ui-url = env(ui_url) | .external-controller = env(api_listen) | .secret = env(api_secret) | .profile.store-selected = env(selection_cache) == 1 |
 		.allow-lan = env(allow_lan) == 1 | .port = env(http_port) | .socks-port = env(socks_port) | .mixed-port = env(mixed_port) | .redir-port = env(redir_port) | .tproxy-port = env(tproxy_port) |
 		.tun.stack = env(tun_stack) | .tun.device = env(tun_device) | .tun.mtu = env(tun_mtu) | .tun.gso = env(tun_gso) == 1 | .tun.gso-max-size = env(tun_gso_max_size) | .tun.endpoint-independent-nat = env(tun_endpoint_independent_nat) == 1 |
 		.dns.enable = env(dns_enable) | .dns.listen = env(dns_listen) | .dns.enhanced-mode = env(dns_mode) | .dns.fake-ip-range = env(fake_ip_range) | .profile.store-fake-ip = env(fake_ip_cache) == 1 |
-		.dns.ipv6 = env(dns_ipv6) == 1 | .dns.use-system-hosts = env(dns_system_hosts) == 1 | .dns.use-hosts = env(dns_hosts) == 1 |
-		.sniffer.enable = env(sniffer) == 1 | .sniffer.force-dns-mapping = env(sniff_dns_mapping) == 1 | .sniffer.parse-pure-ip = env(sniff_pure_ip) == 1 | .sniffer.override-destination = env(sniffer_overwrite_dest) == 1 |
+		.dns.respect-rules = env(dns_respect_rules) == 1 | .dns.ipv6 = env(dns_ipv6) == 1 | .dns.use-system-hosts = env(dns_system_hosts) == 1 | .dns.use-hosts = env(dns_hosts) == 1 |
 		.geodata-mode = env(geoip_format) == "dat" | .geodata-loader = env(geodata_loader) | .geox-url.geosite = env(geosite_url) | .geox-url.mmdb = env(geoip_mmdb_url) | .geox-url.geoip = env(geoip_dat_url) | .geox-url.asn = env(geoip_asn_url) |
 		.geo-auto-update = env(geox_auto_update) == 1 | .geo-update-interval = env(geox_update_interval)
 		' "$RUN_PROFILE_PATH"
@@ -209,7 +167,8 @@ start_service() {
 			config_foreach mixin_authentications "authentication"
 		fi
 		if [ "$fake_ip_filter" == 1 ]; then
-			yq -M -i 'del(.dns.fake-ip-filter)' "$RUN_PROFILE_PATH"
+			fake_ip_filter_mode="$fake_ip_filter_mode" \
+			yq -M -i 'del(.dns.fake-ip-filter) | .dns.fake-ip-filter-mode = env(fake_ip_filter_mode)' "$RUN_PROFILE_PATH"
 			config_list_foreach "mixin" "fake_ip_filters" mixin_fake_ip_filters
 		fi
 		if [ "$hosts" == 1 ]; then
@@ -220,19 +179,9 @@ start_service() {
 			yq -M -i 'del(.dns.default-nameserver) | del(.dns.proxy-server-nameserver) | del(.dns.nameserver) | del(.dns.fallback)' "$RUN_PROFILE_PATH"
 			config_foreach mixin_nameservers "nameserver"
 		fi
-		if [ "$dns_fallback_filter" == 1 ]; then
-			yq -M -i '.dns.fallback-filter.geoip = true | del(.dns.fallback-filter.geoip-code) | del(.dns.fallback-filter.geosite) | del(.dns.fallback-filter.ipcidr) | del(.dns.fallback-filter.domain)' "$RUN_PROFILE_PATH"
-			config_foreach mixin_fallback_filters "fallback_filter"
-		fi
 		if [ "$dns_nameserver_policy" == 1 ]; then
 			yq -M -i 'del(.dns.nameserver-policy)' "$RUN_PROFILE_PATH"
 			config_foreach mixin_nameserver_policies "nameserver_policy"
-		fi
-		if [ "$sniffer" == 1 ]; then
-			yq -M -i 'del(.sniffer.force-domain) | del(.sniffer.skip-domain) | del(.sniffer.sniff)' "$RUN_PROFILE_PATH"
-			config_list_foreach "mixin" "sniffer_force_domain_name" mixin_sniffer_domain_name "force-domain"
-			config_list_foreach "mixin" "sniffer_ignore_domain_name" mixin_sniffer_domain_name "skip-domain"
-			config_foreach mixin_sniffs "sniff"
 		fi
 		# mixin file
 		if [ -s "$MIXIN_FILE_PATH" ]; then
@@ -485,24 +434,6 @@ mixin_nameserver() {
 	nameserver="$1" type="$2" yq -M -i '.dns.[env(type)] += [env(nameserver)]' "$RUN_PROFILE_PATH"
 }
 
-mixin_fallback_filters() {
-	local section="$1"
-
-	local enabled
-	config_get_bool enabled "$section" "enabled" 0
-	config_get type "$section" "type"
-
-	if [ "$enabled" == 0 ]; then
-		return
-	fi
-
-	config_list_foreach "$section" "value" mixin_fallback_filter "$type"
-}
-
-mixin_fallback_filter() {
-	value="$1" type="$2" yq -M -i '.dns.fallback-filter.[env(type)] += [env(value)]' "$RUN_PROFILE_PATH"
-}
-
 mixin_nameserver_policies() {
 	local section="$1"
 
@@ -519,30 +450,6 @@ mixin_nameserver_policies() {
 
 mixin_nameserver_policy() {
 	nameserver="$1" matcher="$2" yq -M -i '.dns.nameserver-policy.[env(matcher)] += [env(nameserver)]' "$RUN_PROFILE_PATH"
-}
-
-mixin_sniffer_domain_name() {
-	domain_name="$1" type="$2" yq -M -i '.sniffer.[env(type)] += [env(domain_name)]' "$RUN_PROFILE_PATH"
-}
-
-mixin_sniffs() {
-	local section="$1"
-
-	local enabled protocol overwrite_dest
-	config_get_bool enabled "$section" "enabled" 0
-	config_get protocol "$section" "protocol"
-	config_get_bool overwrite_dest "$section" "overwrite_dest" 0
-
-	if [ "$enabled" == 0 ]; then
-		return
-	fi
-
-	protocol="$protocol" overwrite_dest="$overwrite_dest" yq -M -i '.sniffer.sniff.[env(protocol)].override-destination = env(overwrite_dest) == 1' "$RUN_PROFILE_PATH"
-	config_list_foreach "$section" "port" mixin_sniff "$protocol"
-}
-
-mixin_sniff() {
-	port="$1" protocol="$2" yq -M -i '.sniffer.sniff.[env(protocol)].ports += [env(port)]' "$RUN_PROFILE_PATH"
 }
 
 add_acl_ip() {
